In [1]:
import numpy as np

In [2]:
lst=[1,2,3]

In [3]:
np.array(lst)#Converts an array into list

array([1, 2, 3])

In [4]:
Arr=np.array(lst)

In [5]:
print(Arr)

[1 2 3]


In [6]:
type(Arr)

numpy.ndarray

In [7]:
Arr2=np.arange(0,20,2)#creates a array of numbers between 0,20 with the step of 2

In [8]:
print(Arr2)

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
arr3=np.arange(0,25)
arr3.reshape(5,5)
#we can reshape the array in our own way, just make sure that our data fits into the array size.
#else an array is returned. 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,5))
#creates a 2D array of ones of a tuple(rows,colums)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full(10,5)
#IT will generate an array of number 5 repeated 10 times. 

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [13]:
np.linspace(0,10,3)
#creates an array with equal spacing of (3) between 0 and 10, both inclusive

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [15]:
np.linspace(0,9,4)

array([0., 3., 6., 9.])

In [16]:
np.eye(4)
#identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)
#It returns an array filled with random numbers between 0 and 1 with the shape of 5.

array([0.41409391, 0.85876144, 0.39169755, 0.83757715, 0.81685062])

In [18]:
np.random.randn(5,5)
#It returns an array with standard random numbers between 0 and 1 with the shape of (5,5)

array([[ 0.19743686, -0.00424977,  1.15265562,  0.25459558, -0.7109306 ],
       [-0.40939912, -0.92715225,  0.03910089,  0.1662082 , -2.708758  ],
       [-1.05593208, -1.39480802, -0.33380676, -0.3772456 ,  1.31074826],
       [ 0.98800826,  0.95250959,  0.98215953,  0.48319755, -1.24884734],
       [ 0.03192523,  1.91603504,  0.82282144, -1.82757854, -1.50160773]])

In [19]:
np.random.randint(2,5,(2,5))
#returns a single number between the start point(2)(inclusive) and end point(5)(exclusive) randomly.
#It will return an array of random numbers if we give the end value too(5) or can return in a shape(2,5).

array([[2, 4, 4, 2, 3],
       [2, 2, 4, 3, 3]])

In [20]:
#If we want to include the seed for the random numbers so that we get the same data every time we use random. 
np.random.seed(43)
np.random.randint(4)

0

In [21]:
Arr.max()

np.int64(3)

In [22]:
arr=np.random.randint(0,101,10)

In [23]:
print(arr)

[64 49 21 58 16 51 17 59 91 66]


In [24]:
arr.max()#tells the maximum number of the array
arr.argmax()#returns the index of the maximum number in the array

np.int64(8)

In [25]:
arr.min()#tells the minimum number in the array
arr.argmin()#returns the index of the minimum number in the array

np.int64(4)

In [26]:
arr.dtype#It returns the datatype of the numbers in the array. 

dtype('int64')

In [27]:
arr.shape

(10,)

In [28]:
arr=arr.reshape((2,5))

In [32]:
print(arr)

[[64 49 21 58 16]
 [51 17 59 91 66]]


In [33]:
arr.shape

(2, 5)

In [ ]:
np.random.randn