Arrays: Indexing and Slicing

In [2]:
import numpy as np

In [3]:
arr= np.arange(0,11)

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [5]:
arr[5]

np.int64(5)

In [6]:
arr[1:5:2]

array([1, 3])

In [7]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5]=100 
# this is not possible to do in a simple list 

When we assign a value of the same array to a different object. It points to the same array.
It is visible from this exercise.

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
slice_of_arr=arr[0:5]

In [11]:
slice_of_arr[:]=100

In [12]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

To avoid changing the values of the original array, we need to make a copy of the original array. 
which can be done using the copy function.

In [14]:
arr_copy=arr.copy()

In [15]:
arr_copy[:]=100

In [16]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Now, we can see that the value of the array didn't get changed. even when we perform any operations on its copy. 

NOW, WE WILL LEARN HOW TO DO THE INDEX AND SELECTION FOR A 2D ARRAY

In [18]:
arr_2d=np.random.randint(0,25,(3,3))

In [19]:
arr_2d

array([[22,  4, 12],
       [17,  6, 13],
       [ 7, 11, 18]])

In [27]:
arr_2d[0]

array([22,  4, 12])

In [29]:
arr_2d[0,2]
# arr_2d[0][2] will do the same thing. 

np.int64(12)

In [32]:
arr_2d[:2,1:]
# We can perform slicing at both rows and columns at once. 

array([[ 4, 12],
       [ 6, 13]])

Here We are starting with Brodcasting Arrays with conditional statements. 

In [38]:
arr1=np.arange(1,11)

In [39]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr1[arr1>4]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
#This returns a boolean Array, which if passed through an index value for array will return the values with true.
arr1>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])