In [55]:
import numpy as np

In [56]:
arr=np.arange(0,10)

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#if I want to add an integer value to all the elements
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [60]:
arr+arr
#Both Arrays should be of same shape. 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
arr*arr
#Both arrays should be of same shape. 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [62]:
#If we perform a division by 0 in numpy Arrays, It will return a warning not a full error. 
arr/arr

/var/folders/bs/j5cp13hj6yx_8lchq3x3h6800000gn/T/ipykernel_19562/368580696.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

NAN = Not a Number

In [63]:
1/0# in python this will result into an error. 

ZeroDivisionError: division by zero

In [ ]:
#although if performed by numpy, no error is made. Just a warning is given. 
1/arr

INF= Infinity

We can also perform Mathematical operations on Arrays. 

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [65]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [66]:
np.log(arr)

/var/folders/bs/j5cp13hj6yx_8lchq3x3h6800000gn/T/ipykernel_19562/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [67]:
arr.sum()

np.int64(45)

In [68]:
arr.mean()

np.float64(4.5)

In [69]:
arr.std()

np.float64(2.8722813232690143)

In [70]:
arr.var()

np.float64(8.25)

In [71]:
arr.max()

np.int64(9)

In [72]:
arr.min()

np.int64(0)

In [73]:
arr.argmin()

np.int64(0)

In [74]:
arr.argmax()

np.int64(9)

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
arr2=np.arange(0,25).reshape(5,5)

In [84]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
arr2.sum()

np.int64(300)

In [79]:
#It performs operation across Rows
arr2.sum(axis=0)

array([50, 55, 60, 65, 70])

In [80]:
#It performs operation acroos Columns
arr2.sum(axis=1)

array([ 10,  35,  60,  85, 110])